import os
import time
from pathlib import Path
from dotenv import load_dotenv
from google import genai
from google.genai import types

# Load .env sitting in the same folder as this script
env_path = Path(__file__).resolve().parent / ".env"
load_dotenv(dotenv_path=env_path)

api_key = os.getenv("GEMINI_API_KEY")

if not api_key:
    raise RuntimeError("GEMINI_API_KEY not found in .env")

client = genai.Client(api_key=api_key)

# Specify model
model = "models/gemini-3.5-flash-lite"


def get_stock_price(ticker: str) -> str:
    """Retrieves current stock price for a given ticker symbol."""
    print(f"\n[Tool Execution] get_stock_price(ticker='{ticker}')")
    
    prices = {
        "AAPL": 225.50,
        "GOOGL": 175.25,
        "MSFT": 410.00,
    }
    ticker_upper = ticker.upper()
    if ticker_upper in prices:
        result = f"Current price of {ticker_upper} is ${prices[ticker_upper]:.2f}"
    else:
        result = f"Price data for ticker '{ticker}' is unavailable."

    print(f"[Tool Result] {result}")
    return result


def calculate_portfolio_value(shares: int, price: float) -> str:
    """Calculates total portfolio value given number of shares and price per share."""
    print(f"\n[Tool Execution] calculate_portfolio_value(shares={shares}, price=${price})")
    total = shares * price
    result = f"Total value for {shares} shares at ${price:.2f} each is ${total:.2f}"
    print(f"[Tool Result] {result}")
    return result


# Map function names to actual Python functions for manual dispatch
tool_map = {
    "get_stock_price": get_stock_price,
    "calculate_portfolio_value": calculate_portfolio_value,
}

# Configure system instruction and register tools with Automatic Function Calling DISABLED
config = types.GenerateContentConfig(
    system_instruction=(
        "You are a ReAct financial assistant. Reason step-by-step using Thought, Action, "
        "and Observation steps. Execute tools manually when calculation or stock data is required."
    ),
    tools=[get_stock_price, calculate_portfolio_value],
    automatic_function_calling=types.AutomaticFunctionCallingConfig(disable=True),
)

print("Creating chat session for Manual ReAct Agent...")
chat = client.chats.create(model=model, config=config)

prompt = "How much would 50 shares of AAPL cost at its current price?"
print(f"User Prompt:\n'{prompt}'\n")

# Send initial prompt to agent
response = chat.send_message(prompt)

step = 1
# Manual ReAct Loop (Thought -> Action -> Observation)
while True:
    print(f"--- ReAct Turn {step} ---")

    # Output text thinking/reasoning if generated by Gemini
    if response.text:
        print(f"[Agent Thought/Text]:\n{response.text}")

    # Process tool call requests from Gemini if present
    if response.function_calls:
        function_responses = []
        for call in response.function_calls:
            print(f"[Agent Action Request]: Call '{call.name}' with args {call.args}")

            if call.name in tool_map:
                # Execute the tool function locally
                tool_func = tool_map[call.name]
                tool_output = tool_func(**call.args)

                # Format function response payload
                function_responses.append(
                    types.Part.from_function_response(
                        name=call.name,
                        response={"result": tool_output}
                    )
                )

        print("\n[Sending Tool Observation back to Gemini...]")
        time.sleep(1)

        # Send tool execution results back to conversation history
        response = chat.send_message(function_responses)
        step += 1
    else:
        # No remaining tool requests; agent provided final answer
        print("\n=== FINAL AGENT RESPONSE ===")
        print(response.text)
        break

time.sleep(3)