import asyncio
import time
import warnings
from pathlib import Path
from dotenv import load_dotenv

warnings.filterwarnings("ignore")

# Load environment variables
env_path = Path(__file__).resolve().parent.parent / ".env"
load_dotenv(dotenv_path=env_path)

from google.adk import Runner
from google.adk.sessions import InMemorySessionService
from google.genai import types

from agent import root_agent

session_service = InMemorySessionService()
runner = Runner(
    agent=root_agent,
    app_name="workflow_app",
    session_service=session_service
)

async def send_message(user_id: str, session_id: str, prompt_text: str, label: str = "User"):
    print(f"\n{label}: {prompt_text}")
    user_content = types.Content(
        role="user",
        parts=[types.Part.from_text(text=prompt_text)]
    )

    current_agent = None

    # Inspect event streams from the ADK Runner
    async for event in runner.run_async(
        user_id=user_id,
        session_id=session_id,
        new_message=user_content
    ):
        # 1. Identify which agent authored this turn/event
        event_author = (
            getattr(event, "author", None) 
            or getattr(event, "agent_name", None) 
            or "Workflow"
        )

        # 2. Print a visual section header when the active agent changes
        if event_author != current_agent:
            current_agent = event_author
            print(f"\n\n🤖 [Executing Agent: {current_agent}]")
            print("-" * 45)

        # 3. Stream the output generated by the active agent
        if hasattr(event, "content") and event.content and event.content.parts:
            for part in event.content.parts:
                if part.text:
                    print(part.text, end="", flush=True)
    print("\n")

async def main():
    user_id = "user_123"
    session_id = "session_001"

    await session_service.create_session(
        app_name="workflow_app",
        user_id=user_id,
        session_id=session_id
    )

    # --- Step 1: Pre-entered Demo Turns ---
    print("=== Step 1: Pre-entered Demo Turns ===")
    await send_message(
        user_id, session_id,
        "Topic: Quantum Computing Basics",
        label="Pre-entered Turn 1"
    )
    time.sleep(2)

    await send_message(
        user_id, session_id,
        "Topic: Renewable Energy Storage",
        label="Pre-entered Turn 2"
    )
    time.sleep(2)

    # --- Step 2: Interactive Terminal Session ---
    print("=" * 50)
    print("=== Step 2: Interactive Session ===")
    print("Type your input (or 'exit'/'quit' to stop):")

    while True:
        try:
            user_input = input("\nYou: ").strip()
            if not user_input:
                continue
            if user_input.lower() in ("exit", "quit"):
                print("Ending session.")
                break

            await send_message(user_id, session_id, user_input, label="You")
            time.sleep(2)
        except (KeyboardInterrupt, EOFError):
            break

if __name__ == "__main__":
    asyncio.run(main())